#!/usr/bin/env python3
"""
Unified RUL Dashboard for 1020+ Rogers HVAC Sites.
Displays Mode 3 (rolling median) analysis only.
Reads from sites_data.json (generated by query_sites.py).
"""

import json
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime
from pathlib import Path

st.set_page_config(
    page_title="Rogers HVAC RUL Dashboard",
    page_icon="🌡️  ",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
    /* Main app background */
    .stApp { background-color: #ffffff; }

    /* Sidebar styling - all text elements */
    [data-testid="stSidebar"] { background-color: #1e3a5f; }

    /* Sidebar markdown and text */
    [data-testid="stSidebar"] .stMarkdown,
    [data-testid="stSidebar"] .stMarkdown * {
        color: #ffffff !important;
    }

    /* Sidebar labels */
    [data-testid="stSidebar"] label {
        color: #e0e7ff !important;
        font-weight: 500 !important;
    }

    /* Sidebar selectbox styling */
    [data-testid="stSidebar"] .stSelectbox label {
        color: #e0e7ff !important;
        font-size: 0.78rem !important;
        letter-spacing: 0.08em !important;
        text-transform: uppercase !important;
        font-weight: 600 !important;
    }
    [data-testid="stSidebar"] .stSelectbox div {
        color: #ffffff !important;
    }

    /* Sidebar radio styling */
    [data-testid="stSidebar"] .stRadio label {
        color: #e0e7ff !important;
        font-weight: 500 !important;
    }
    [data-testid="stSidebar"] .stRadio span {
        color: #ffffff !important;
    }

    /* Sidebar slider styling */
    [data-testid="stSidebar"] .stSlider label {
        color: #e0e7ff !important;
        font-weight: 500 !important;
    }
    [data-testid="stSidebar"] .stSlider {
        color: #ffffff !important;
    }

    /* Sidebar text input */
    [data-testid="stSidebar"] .stTextInput label {
        color: #e0e7ff !important;
        font-weight: 500 !important;
    }
    [data-testid="stSidebar"] input {
        background-color: #2d4a7a !important;
        color: #ffffff !important;
        border-color: #4f7cff !important;
    }
    [data-testid="stSidebar"] input::placeholder {
        color: #a5b4fc !important;
    }

    /* Main content number input styling */
    .stNumberInput input {
        color: #ffffff !important;
        background-color: #2d2d2d !important;
        border-color: #4f7cff !important;
    }
    .stNumberInput input::placeholder {
        color: #a5a5a5 !important;
    }
    .stNumberInput label {
        color: #1a202c !important;
    }

    /* Main content - explicit dark text */
    body,
    .stApp,
    .stMarkdown p,
    [data-testid="stVerticalBlock"] > div > p {
        color: #1a202c !important;
    }

    .stMarkdown,
    .stMarkdown * {
        color: #1a202c !important;
    }

    .stMarkdown p,
    .stMarkdown h1,
    .stMarkdown h2,
    .stMarkdown h3,
    .stMarkdown h4,
    .stMarkdown h5,
    .stMarkdown h6 {
        color: #1a202c !important;
    }

    /* Ensure text content is dark */
    main {
        color: #1a202c !important;
    }

    main p, main div, main span {
        color: #1a202c !important;
    }

    /* Metric cards */
    .metric-card {
        background: #ffffff;
        border-radius: 12px;
        padding: 20px 24px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        border-left: 5px solid #4f7cff;
        min-height: 95px;
        box-sizing: border-box;
    }
    .metric-card.warn { border-left-color: #f59e0b; }
    .metric-card.danger { border-left-color: #ef4444; }
    .metric-card .label {
        font-size: 0.7rem;
        color: #6b7280 !important;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        margin-bottom: 8px;
        font-weight: 700;
    }
    .metric-card .value {
        font-size: 1.8rem;
        font-weight: 800;
        color: #1a202c !important;
    }
    .metric-card .sub {
        font-size: 0.75rem;
        color: #6b7280 !important;
        margin-top: 4px;
        font-weight: 500;
    }

    /* Section headers */
    .section-header {
        font-size: 0.75rem;
        font-weight: 800;
        color: #1a202c !important;
        text-transform: uppercase;
        letter-spacing: 0.12em;
        margin: 24px 0 14px 0;
        padding-bottom: 10px;
        border-bottom: 2px solid #e5e7eb;
    }

    /* Expanders and containers */
    [data-testid="stExpander"] {
        background-color: #ffffff !important;
        border: 1px solid #e5e7eb !important;
        border-radius: 8px !important;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05) !important;
    }
    
    [data-testid="stExpander"] summary,
    [data-testid="stExpander"] summary:hover,
    [data-testid="stExpander"] summary:focus,
    [data-testid="stExpander"] summary:active,
    [data-testid="stExpander"] > button,
    [data-testid="stExpander"] > button:hover,
    [data-testid="stExpander"] > button:focus,
    [data-testid="stExpander"] > button:active {
        background-color: #ffffff !important;
        color: #1a202c !important;
        font-weight: 600 !important;
    }

    [data-testid="stExpander"] summary p,
    [data-testid="stExpander"] > button p {
        color: #1a202c !important;
    }
    
    [data-testid="stExpanderDetails"] {
        color: #1a202c !important;
        background-color: #fafbfc !important;
    }
    [data-testid="stExpanderDetails"] * {
        color: #1a202c !important;
    }

    /* Mode description box */
    .mode-description {
        background: #f8fafc;
        border-radius: 8px;
        padding: 14px 18px;
        border-left: 4px solid #4f7cff;
        margin-bottom: 1rem;
        font-size: 0.85rem;
        color: #374151 !important;
        line-height: 1.7;
    }

    /* Titles and headers */
    h1 {
        color: #1a202c !important;
        font-weight: 800 !important;
        letter-spacing: -0.02em !important;
        margin-bottom: 1rem !important;
    }
    h2 {
        color: #1a202c !important;
        font-weight: 700 !important;
        margin-bottom: 1.2rem !important;
        margin-top: 0.5rem !important;
    }
    h3 {
        color: #1a202c !important;
        font-weight: 700 !important;
        margin-top: 1rem !important;
    }

    /* Info and warning boxes */
    .stInfo, .stWarning, .stSuccess, .stError {
        background-color: #f0f9ff !important;
        border-radius: 8px !important;
        color: #1a202c !important;
    }
    .stInfo {
        border-left: 4px solid #4f7cff !important;
        color: #1a202c !important;
    }
    .stInfo * {
        color: #1a202c !important;
    }
    .stWarning { border-left: 4px solid #f59e0b !important; }
    .stWarning * { color: #1a202c !important; }
    .stSuccess { border-left: 4px solid #10b981 !important; }
    .stSuccess * { color: #1a202c !important; }
    .stError { border-left: 4px solid #ef4444 !important; }
    .stError * { color: #1a202c !important; }

    /* Dataframe styling */
    [data-testid="stDataFrame"] {
        background-color: #ffffff !important;
        color: #1a202c !important;
    }
    [data-testid="stDataFrame"] * {
        color: #1a202c !important;
    }

    /* Plotly graphs */
    .js-plotly-plot {
        margin-top: 1.5rem;
        margin-bottom: 1.5rem;
    }

    /* Links */
    a { color: #4f7cff !important; text-decoration: none !important; }
    a:hover { text-decoration: underline !important; }

    /* Hide default elements EXCEPT header (header has the sidebar toggle) */
    #MainMenu, footer { visibility: hidden; }

    /* Block container */
    .block-container {
        padding-top: 2rem !important;
        max-width: 100% !important;
        padding-left: 2rem !important;
        padding-right: 2rem !important;
    }

    /* Column spacing */
    [data-testid="column"] { padding: 0 10px !important; }

    /* Force main content text colors for all elements */
    [role="main"] {
        color: #1a202c !important;
    }
    [role="main"] * {
        color: #1a202c !important;
    }

    /* Target any remaining white/unwanted text */
    .stText, .stInfo * {
        color: #1a202c !important;
    }

    /* Sidebar input container styling */
    [data-testid="stSidebar"] .stMultiSelect,
    [data-testid="stSidebar"] .stSelectbox,
    [data-testid="stSidebar"] .stTextInput,
    [data-testid="stSidebar"] .stSlider,
    [data-testid="stSidebar"] .stRadio {
        color: #ffffff !important;
    }

    [data-testid="stSidebar"] .stTextInput input,
    [data-testid="stSidebar"] [class*="stTextInput"] input,
    [data-testid="stSidebar"] input[type="text"] {
        color: #ffffff !important;
        background-color: #2d4a7a !important;
        border: 1px solid #4f7cff !important;
    }

    /* Override Streamlit theme for sidebar selections */
    [data-testid="stSidebar"] .stSelectbox [data-baseweb="select"] {
        color: #ffffff !important;
    }

    [data-testid="stSidebar"] .stRadio [data-testid="stRadio"] {
        color: #ffffff !important;
    }

    /* Main slider label styling - make labels black and visible */
    .stSlider label {
        color: #000000 !important;
        font-weight: 700 !important;
        font-size: 0.9rem !important;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# LOAD DATA
# ============================================================================

@st.cache_data(ttl=300)
def load_sites_data(json_file='sites_data.json'):
    """Load aggregated site data from JSON, with preprocessing for CSV-based sites."""
    if not Path(json_file).exists():
        st.error(f"Data file not found: {json_file}")
        st.info("Run `python3 query_sites.py` on the Bell laptop to generate this file.")
        st.stop()

    with open(json_file) as f:
        data = json.load(f)

    # Preprocess CSV-based sites (W2567, etc.)
    for site_id, site_result in data.get('sites', {}).items():
        # Convert W2567's native filter_change format to dashboard's expected format
        if site_result.get('data_source') == 'csv' and site_result.get('filter_change'):
            fc_meta = site_result['filter_change']
            if fc_meta.get('detected'):
                # Get the hours from cumulative_adjusted_hours array at the episode index
                cumul_hours = site_result.get('cumulative_adjusted_hours', [])
                episode_idx = fc_meta.get('episode_index')
                hours_at_change = 0.0
                if episode_idx is not None and isinstance(cumul_hours, list) and episode_idx < len(cumul_hours):
                    hours_at_change = float(cumul_hours[episode_idx])

                # Convert to filter_change_detected format
                site_result['filter_change_detected'] = {
                    'episode_idx': episode_idx,
                    'hours': hours_at_change,
                    'drop': (fc_meta.get('pre_change_delta_t') or 0) - (fc_meta.get('post_change_delta_t') or 0),
                    'before_dt': fc_meta.get('pre_change_delta_t'),
                    'after_dt': fc_meta.get('post_change_delta_t')
                }

    return data


def recalculate_rul(site_result, new_failure_dt, rolling_window=1, filter_change_hours=None):
    """
    Recalculate RUL for a site using a custom failure ΔT threshold.
    Uses trend line to determine current ΔT state.
    Applies rolling median filter to smooth noisy max_deltas.
    Returns updated site_result with new rul_days and urgency.
    """
    site_copy = site_result.copy()

    # For CSV sites with filter_change, still calculate RUL even if success=False
    is_csv_with_filter = (site_result.get('data_source') == 'csv' and
                         site_result.get('filter_change') is not None)

    if not site_result.get('success') and not is_csv_with_filter:
        return site_copy

    # Apply rolling median filter to smooth max_deltas
    max_deltas = site_result.get('max_deltas', [])
    cumul_hours = site_result.get('cumulative_adjusted_hours', [])

    # Detect sudden drops in max_deltas (indicative of filter change)
    filter_change_detected = None
    if len(max_deltas) >= 2:
        for i in range(1, len(max_deltas)):
            drop = max_deltas[i - 1] - max_deltas[i]
            if drop >= 5.0:  # 5°C drop threshold
                filter_change_detected = {
                    'episode_idx': i,
                    'hours': float(cumul_hours[i]),
                    'drop': float(drop),
                    'before_dt': float(max_deltas[i - 1]),
                    'after_dt': float(max_deltas[i])
                }
                break  # Use first detected change

    site_copy['filter_change_detected'] = filter_change_detected

    # Refit trend line with smoothed data (or split if filter change confirmed)
    intercept = None
    if filter_change_hours is not None and len(max_deltas) >= 2 and len(cumul_hours) == len(max_deltas):
        # Split at confirmed filter change point
        split_idx = next((i for i, h in enumerate(cumul_hours) if h >= filter_change_hours), None)
        if split_idx and split_idx > 0 and split_idx < len(max_deltas) - 1:
            # Apply rolling median separately to each segment (don't carry over)
            pre_max_deltas = max_deltas[:split_idx]
            post_max_deltas = max_deltas[split_idx:]

            if rolling_window > 1 and len(pre_max_deltas) >= rolling_window:
                pre_smoothed = []
                for i in range(len(pre_max_deltas)):
                    start = max(0, i - rolling_window // 2)
                    end = min(len(pre_max_deltas), i + rolling_window // 2 + 1)
                    median_val = float(np.median(pre_max_deltas[start:end]))
                    pre_smoothed.append(median_val)
                pre_max_deltas = pre_smoothed

            if rolling_window > 1 and len(post_max_deltas) >= rolling_window:
                post_smoothed = []
                for i in range(len(post_max_deltas)):
                    start = max(0, i - rolling_window // 2)
                    end = min(len(post_max_deltas), i + rolling_window // 2 + 1)
                    median_val = float(np.median(post_max_deltas[start:end]))
                    post_smoothed.append(median_val)
                post_max_deltas = post_smoothed

            # Fit to post-filter-change data (more relevant for current RUL)
            coeffs = np.polyfit(cumul_hours[split_idx:], post_max_deltas, 1)
            slope, intercept = coeffs[0], coeffs[1]
            baseline_dt = post_max_deltas[0]
            site_copy['filter_change_hours'] = float(filter_change_hours)
            # Update site_copy with post-filter regression values for display
            site_copy['slope'] = float(slope)
            site_copy['intercept_recalc'] = float(intercept)
            site_copy['baseline_dt'] = float(baseline_dt)
            site_copy['dual_trend'] = {
                'split_hours': float(filter_change_hours),
                'pre_split_coeffs': np.polyfit(cumul_hours[:split_idx], pre_max_deltas, 1).tolist() if split_idx > 1 else None,
                'post_split_coeffs': [float(slope), float(intercept)]
            }
        else:
            # Can't split, use whole dataset
            smoothed_deltas = max_deltas
            if rolling_window > 1 and len(max_deltas) >= rolling_window:
                smoothed_deltas = []
                for i in range(len(max_deltas)):
                    start = max(0, i - rolling_window // 2)
                    end = min(len(max_deltas), i + rolling_window // 2 + 1)
                    median_val = float(np.median(max_deltas[start:end]))
                    smoothed_deltas.append(median_val)
            coeffs = np.polyfit(cumul_hours, smoothed_deltas, 1)
            slope, intercept = coeffs[0], coeffs[1]
            baseline_dt = smoothed_deltas[0]
            # Update site_copy with recalculated values for display
            site_copy['slope'] = float(slope)
            site_copy['intercept_recalc'] = float(intercept)
            site_copy['baseline_dt'] = float(baseline_dt)
    elif len(max_deltas) >= 2 and len(cumul_hours) == len(max_deltas):
        # No filter change - apply rolling median to entire dataset
        smoothed_deltas = max_deltas
        if rolling_window > 1 and len(max_deltas) >= rolling_window:
            smoothed_deltas = []
            for i in range(len(max_deltas)):
                start = max(0, i - rolling_window // 2)
                end = min(len(max_deltas), i + rolling_window // 2 + 1)
                median_val = float(np.median(max_deltas[start:end]))
                smoothed_deltas.append(median_val)
        coeffs = np.polyfit(cumul_hours, smoothed_deltas, 1)
        slope, intercept = coeffs[0], coeffs[1]
        baseline_dt = smoothed_deltas[0]
    else:
        slope = site_result.get('slope', 0)
        intercept = site_result.get('intercept', 0)
        baseline_dt = site_result.get('baseline_dt', 0)

    current_hours = site_result.get('total_adjusted_hours', 0)

    # Calculate current_dt from trend line: intercept + slope * hours
    current_dt = intercept + slope * current_hours if current_hours >= 0 else intercept

    # Store for display
    site_copy['current_dt'] = float(current_dt)
    site_copy['intercept_recalc'] = float(intercept) if intercept else site_result.get('intercept', 0)

    if slope <= 0:
        # For CSV sites with recent filter change, calculate conservative RUL
        if is_csv_with_filter and site_result.get('filter_change', {}).get('detected'):
            # Use current ΔT from the last episode
            max_deltas = site_result.get('max_deltas', [])
            current_dt = float(max_deltas[-1]) if max_deltas else 5.0

            site_copy['current_dt'] = current_dt
            site_copy['failure_dt'] = new_failure_dt

            # Conservative estimate: assume 0.01°C degradation per adjusted hour
            # (new filter degrades slowly)
            hours_to_failure = (new_failure_dt - current_dt) / 0.01 if (new_failure_dt - current_dt) > 0 else 9999
            avg_hours_per_day = site_result.get('avg_adjusted_hours_per_day', 1.0)
            rul_days = hours_to_failure / avg_hours_per_day if avg_hours_per_day > 0 else 9999

            site_copy['rul_days'] = max(0, rul_days)
            site_copy['pct_life'] = 0  # New filter, just started

            if rul_days < 14:
                site_copy['urgency'] = 'URGENT'
            elif rul_days < 30:
                site_copy['urgency'] = 'WARNING'
            else:
                site_copy['urgency'] = 'OK'
            return site_copy

        # For regular sites with negative slope: no clear degradation
        site_copy['rul_days'] = 999
        site_copy['urgency'] = 'OK'
        return site_copy

    site_copy['failure_dt'] = new_failure_dt

    if current_dt >= new_failure_dt:
        site_copy['rul_days'] = 0
        site_copy['urgency'] = 'URGENT'
        site_copy['pct_life'] = 100
        return site_copy

    # Convert to days using avg hours per day
    avg_hours_per_day = site_result.get('avg_adjusted_hours_per_day', 1.0)
    hours_to_failure = (new_failure_dt - intercept) / slope if slope > 0 else 999
    remaining_hours = hours_to_failure - current_hours
    rul_days = remaining_hours / avg_hours_per_day if avg_hours_per_day > 0 else 999
    site_copy['rul_days'] = max(0, rul_days)

    # Calculate % filter life based on trend line values
    dt_range = new_failure_dt - intercept
    dt_consumed = current_dt - intercept
    pct_life = max(0, min(100, (dt_consumed / dt_range * 100))) if dt_range > 0 else 0
    site_copy['pct_life'] = pct_life

    if rul_days < 14:
        site_copy['urgency'] = 'URGENT'
    elif rul_days < 30:
        site_copy['urgency'] = 'WARNING'
    else:
        site_copy['urgency'] = 'OK'

    return site_copy


def calculate_pollution_impact_blurb(site_result, all_sites_data):
    """
    Calculate how this site's pollution compares to the site average.
    Returns a blurb explaining the impact on filter degradation.
    Only show if slope is positive (sufficient data).
    """
    if not site_result.get('air_quality'):
        return None

    # Skip if slope is negative (insufficient data)
    if site_result.get('slope', 0) <= 0:
        return None

    # Get regression coefficients
    regression = all_sites_data.get('air_quality_regression', {})
    if not regression or (not regression.get('coefficient_pm25') and not regression.get('coefficient_pm10')):
        return None

    beta_pm25 = regression.get('coefficient_pm25') or 0
    beta_pm10 = regression.get('coefficient_pm10') or 0

    # Calculate site averages for PM2.5 and PM10
    pm25_values = []
    pm10_values = []
    for site_id, result_item in all_sites_data.get('sites', {}).items():
        if result_item.get('air_quality'):
            pm25 = result_item['air_quality'].get('pm25')
            pm10 = result_item['air_quality'].get('pm10')
            if pm25 is not None:
                pm25_values.append(pm25)
            if pm10 is not None:
                pm10_values.append(pm10)

    if not pm25_values or not pm10_values:
        return None

    avg_pm25 = np.mean(pm25_values)
    avg_pm10 = np.mean(pm10_values)

    # This site's pollution
    site_pm25 = site_result['air_quality'].get('pm25')
    site_pm10 = site_result['air_quality'].get('pm10')

    if site_pm25 is None or site_pm10 is None:
        return None

    # Calculate slope impact (degradation rate adjustment)
    slope_impact = (beta_pm25 * (site_pm25 - avg_pm25)) + (beta_pm10 * (site_pm10 - avg_pm10))

    # Convert slope impact to RUL impact in days
    raw_slope = site_result.get('slope', 0.001)
    if raw_slope <= 0:
        return None

    # Approximate RUL impact: assume typical site has ~30 day RUL
    avg_rul_days = 30
    rul_impact_days = (slope_impact / raw_slope) * avg_rul_days

    # Format the blurb
    pm25_diff = site_pm25 - avg_pm25
    pm10_diff = site_pm10 - avg_pm10
    direction = "faster" if rul_impact_days < 0 else "slower"

    blurb = f"**Pollution Impact (vs Site Average):**\n"
    blurb += f"- PM2.5: {site_pm25:.1f} μg/m³ ({pm25_diff:+.1f} vs avg {avg_pm25:.1f})\n"
    blurb += f"- PM10: {site_pm10:.1f} μg/m³ ({pm10_diff:+.1f} vs avg {avg_pm10:.1f})\n"
    blurb += f"\nBased on air quality patterns across all sites, this location's air quality would cause the filter to degrade **{abs(rul_impact_days):.1f} days {direction}** than typical."

    return blurb


def get_model_equation(result):
    """Generate the equation with actual parameters."""
    intercept = result.get('intercept', 0)
    slope = result.get('slope', 0)

    # All sites use 1-factor model
    equation = f"ΔT = {intercept:.2f} + {slope:.4f} × (adj_hours)"
    return equation


# ============================================================================
# DATA LOADING & SIDEBAR CONTROLS
# ============================================================================

data = load_sites_data()
sites = data['sites']

with st.sidebar:
    st.markdown("### ⚙️ Analysis Controls", help="Adjust these parameters to recalculate RUL")
    
    min_duration = st.slider("Min episode duration (min)", 10, 120, 30, step=5)
    fan_threshold = st.slider("Min fan speed (%)", 80, 100, 95, step=1)
    rolling_window = st.slider("Rolling median window (episodes)", 3, 10, 5, step=1)
    failure_dt = st.slider("ΔT at filter failure (°C)", 5.0, 20.0, 10.0, step=0.5)

    st.markdown("---")
    
    st.markdown("### 🔍 Filter & Sort Options")
    urgency_filter = st.multiselect(
        "Urgency Level",
        ['URGENT', 'WARNING', 'OK', 'UNKNOWN'],
        default=['URGENT', 'WARNING', 'OK']
    )
    
    search_term = st.text_input("Search site name/ID", "")
    
    sort_by = st.radio(
        "Sort by",
        ['RUL (ascending)', 'Site Name (A-Z)', 'Urgency + RUL']
    )

# ============================================================================
# MAIN CONTENT
# ============================================================================

st.markdown(f"<h1 style='color: #1a202c; margin-bottom: 0.5rem;'>🌡️  Rogers HVAC Filter RUL Dashboard</h1>", unsafe_allow_html=True)

# Main Dashboard Descriptive Blurb
st.markdown("""
<div style="background-color: #f8fafc; padding: 18px 24px; border-radius: 8px; border-left: 4px solid #4f7cff; margin-bottom: 24px; color: #374151; font-size: 0.95rem; line-height: 1.6; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
    <strong style="color: #1a202c; font-size: 1.05rem;">About This Dashboard</strong><br>
    This tool predicts the Remaining Useful Life (RUL) of HVAC filters across 1020+ sites. It tracks the maximum temperature differential (ΔT) during free cooling events (when fans run at ≥95% speed for at least 30 minutes). Because air resistance scales with fan speed squared, operating hours are adjusted proportionately to model how the filter degrades over time. 
    <br><br>
    The system fits a linear degradation trend to predict when a filter's ΔT will exceed a critical failure threshold (default 10°C). For sites with local air quality data (PM2.5/PM10), the model analyzes if local pollution levels are speeding up or slowing down the filter degradation relative to the network average.
</div>
""", unsafe_allow_html=True)


# ============================================================================
# RECALCULATE WITH NEW PARAMETERS
# ============================================================================

sites_recalc = {}
for site_id, site_result in sites.items():
    # Check if user confirmed filter change for this site
    fc_confirmed = st.session_state.get(f"fc_confirm_{site_id}", False)
    fc_hours = None

    # For CSV sites with filter_change metadata, use default unless user modified it
    is_csv_with_filter = (site_result.get('data_source') == 'csv' and
                         site_result.get('filter_change') is not None)
    if is_csv_with_filter and site_result.get('filter_change_detected'):
        # Use default from CSV metadata
        fc_hours = site_result['filter_change_detected'].get('hours')

    # If user confirmed/modified the filter change, override with session state
    if fc_confirmed:
        fc_hours = st.session_state.get(f"fc_hours_{site_id}", fc_hours)

    sites_recalc[site_id] = recalculate_rul(site_result, failure_dt, rolling_window, filter_change_hours=fc_hours)

success_count = len([s for s in sites_recalc.values() if s.get('success')])
st.markdown(f"<h2 style='color: #1a202c; margin-bottom: 1.5rem;'>Status — {success_count} Sites Analyzed</h2>", unsafe_allow_html=True)

# Model Architecture Explanation
with st.expander("📚 **Model Architecture & Methodology**", expanded=False):
    st.markdown("""
<div style="color: #1a202c; line-height: 1.9; font-size: 0.95rem;">

### Filter Degradation Tracking

**How We Monitor Filter Clogging**

Each HVAC system's filter degrades as air is forced through it. We track this degradation by monitoring the temperature differential (ΔT) between supply air and return air during freecooling episodes:

1. **Identify Freecooling Events** — We detect periods where the supply fan speed exceeds the minimum threshold (default: 95%) and the unit is in freecooling mode, lasting at least 30 minutes.

2. **Capture Max Temperature Differential** — During each freecooling episode, we record the maximum ΔT that occurs. A clogged filter causes higher ΔT because air must be forced harder through the restricted filter media.

3. **Track Degradation Over Time** — As the filter accumulates particulates, the max ΔT increases episode after episode. We plot this progression: how does max ΔT change as the filter runs?

---

### Relating Degradation to Runtime (Adjusted Hours)

**Why We Adjust for Fan Speed**

A filter that runs at 50% fan speed produces less air resistance (and thus less degradation) than one at 100% speed. Air resistance scales with fan speed squared:

**Formula:** adjusted_hours = duration_hours × (fan_speed_pct)²

**Examples:**
- 1 hour at 100% fan speed = 1.0 adjusted hours (maximum degradation)
- 1 hour at 50% fan speed = 0.25 adjusted hours (one quarter the impact)
- 1 hour at 75% fan speed = 0.5625 adjusted hours

**Linear Regression Model**

We fit a line through each site's data: **ΔT = β₀ + β₁ × (cumulative adjusted hours)**

- **β₀** (intercept): baseline ΔT when filter is clean
- **β₁** (slope): how fast ΔT increases per adjusted operating hour
- Higher slope = faster degradation = shorter remaining life

The slope directly reveals filter health: a steep slope means the filter clogs quickly; a gentle slope means it's still relatively clean.

---

### Predicting Filter Failure

**When Does the Filter Fail?**

We assume filter failure occurs when ΔT reaches 10°C (adjustable via the dashboard slider). Using the fitted line and the current average operating pattern, we project when ΔT will cross this threshold:

- **RUL (days)** = (Failure ΔT - Current ΔT) / Slope ÷ (Average Adjusted Hours Per Day)

**Example:**
- Current max ΔT: 4°C
- Slope: 0.08°C per adjusted hour
- Average adjusted hours per day: 8
- Remaining adjusted hours: (10 - 4) / 0.08 = 75 adjusted hours
- **RUL: 75 ÷ 8 = 9.4 days** → 🔴 URGENT

---

### Accounting for Air Quality Impact

**Pollution Effect on Filter Life**

Polluted air (high PM10 and PM2.5) causes filters to clog faster than clean air. We quantify this impact by:

1. **Analyzing sites WITH air quality data** — For sites with available coordinates and Weatherbit data, we fit a separate regression to understand the relationship between pollution levels and observed degradation rates (slopes).

2. **Comparing to population average** — Each site's pollution levels (PM2.5 and PM10) are compared to the average across all sites. If a site is cleaner than average, its filter should last longer; if dirtier, it will fail sooner.

3. **Predicting pollution impact** — Using population-level regression coefficients, we calculate how much this site's unique pollution profile would speed up or slow down degradation:
   - **Pollution Impact (days)** = β_PM2.5 × (site PM2.5 - avg PM2.5) + β_PM10 × (site PM10 - avg PM10)
   - Positive impact = faster degradation (shorter RUL)
   - Negative impact = slower degradation (longer RUL)

4. **Sites without air quality data** — No pollution context is available; RUL is based purely on observed ΔT trends and adjusted hours.

**Example:**
- Site's predicted degradation rate difference vs population: +2.3 days faster
- This means: "Your filter will likely fail 2.3 days sooner than a typical site due to your air quality"

---

### Urgency Classification

- 🔴 **URGENT** → RUL < 14 days (Replace immediately)
- 🟡 **WARNING** → 14–30 days (Schedule replacement soon)
- 🟢 **OK** → ≥30 days (Monitor, no action needed)

---

### Data Processing Pipeline

1. **Extract Freecooling Episodes** — Identify periods where fan ≥95%, mode = freecooling, duration ≥30 min
2. **Record Max ΔT** — Capture the maximum temperature differential in each episode
3. **Calculate Adjusted Hours** — Weight runtime by (fan_speed_pct)²
4. **Fit Degradation Line** — Linear regression: max ΔT vs cumulative adjusted hours
5. **Fetch Air Quality** — For sites with coordinates, retrieve 90-day PM10/PM2.5 averages from Weatherbit
6. **Analyze Pollution Correlation** — Fit regression across all sites with AQ data to find pollution coefficients
7. **Predict RUL & Impact** — Project when ΔT hits failure threshold; calculate pollution impact for sites with data
8. **Classify Urgency** — Assign URGENT/WARNING/OK based on RUL days remaining

---

### Data Sources

| Source | Granularity | Purpose |
|--------|------------|---------|
| **InfluxDB** | 1–10 min intervals | HVAC data (fan speed, ΔT, freecooling mode) |
| **Weatherbit API** | Hourly records | Air quality (PM10, PM2.5) — 90-day average |
| **Freecooling Episodes** | 30 min–hours | Periods where filter experiences load |
| **Regression Analysis** | Batch fit (one-time) | Pollution coefficients from population data |
---

</div>
  """, unsafe_allow_html=True)

st.markdown("---")

threshold_info = f"<strong style='color: #1a202c;'>Custom Failure Threshold: {failure_dt}°C</strong>"
if failure_dt != data.get('default_failure_dt', 10.0):
    original_threshold = data.get('default_failure_dt', 10.0)
    threshold_info += f" <span style='color: #6b7280;'>(Original: {original_threshold}°C)</span>"
st.markdown(threshold_info, unsafe_allow_html=True)

# Metrics row
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    urgent_count = sum(1 for s in sites_recalc.values() if s.get('success') and s.get('urgency') == 'URGENT')
    st.markdown(f'<div class="metric-card danger"><div class="label">🔴 URGENT</div><div class="value">{urgent_count}</div><div class="sub">< 14 days</div></div>', unsafe_allow_html=True)

with col2:
    warning_count = sum(1 for s in sites_recalc.values() if s.get('success') and s.get('urgency') == 'WARNING')
    st.markdown(f'<div class="metric-card warn"><div class="label">🟡 WARNING</div><div class="value">{warning_count}</div><div class="sub">14–30 days</div></div>', unsafe_allow_html=True)

with col3:
    ok_count = sum(1 for s in sites_recalc.values() if s.get('success') and s.get('urgency') == 'OK')
    st.markdown(f'<div class="metric-card"><div class="label">🟢 OK</div><div class="value">{ok_count}</div><div class="sub">≥ 30 days</div></div>', unsafe_allow_html=True)

with col4:
    failed_count = sum(1 for s in sites_recalc.values() if not s.get('success'))
    st.markdown(f'<div class="metric-card"><div class="label">⚪ FAILED</div><div class="value">{failed_count}</div><div class="sub">Query error</div></div>', unsafe_allow_html=True)

with col5:
    successful = [s for s in sites_recalc.values() if s.get('success')]
    rul_values = [s.get('rul_days', 0) for s in successful if s.get('rul_days') is not None and isinstance(s.get('rul_days'), (int, float))]
    mean_rul = np.mean(rul_values) if rul_values else 0
    mean_rul_str = f'{mean_rul:.0f}d' if not np.isnan(mean_rul) else '?'
    st.markdown(f'<div class="metric-card"><div class="label">Average RUL</div><div class="value">{mean_rul_str}</div><div class="sub">All sites</div></div>', unsafe_allow_html=True)

st.markdown("---")

# ============================================================================
# SITES TABLE
# ============================================================================

st.markdown(f'<h3 style="color: #1a202c; margin-top: 1.5rem; margin-bottom: 1rem; font-weight: 700;">📊 Sites Status Table</h3>', unsafe_allow_html=True)

table_data = []
for site_id, result in sites_recalc.items():
    # Include successful sites OR CSV sites with filter changes
    is_successful = result.get('success')
    is_csv_with_filter_change = result.get('data_source') == 'csv' and (result.get('filter_change') or result.get('filter_change_detected'))

    if not is_successful and not is_csv_with_filter_change:
        continue

    # For successful sites, check urgency filter; for CSV sites, show regardless
    if is_successful and result.get('urgency') not in urgency_filter:
        continue

    search_str = f"{site_id} {result.get('site_name', '')}".lower()
    if search_term.lower() and search_term.lower() not in search_str:
        continue

    rul = result.get('rul_days', None)

    # Check if pollution effect was applied
    has_pollution_effect = result.get('pollution_effect') is not None
    pollution_indicator = f"({result.get('pollution_effect'):+.3f})" if has_pollution_effect else "—"

    # Air quality info (handle None values)
    aq = result.get('air_quality') or {}
    pm10_str = f"{aq.get('pm10', 0):.1f}" if aq.get('pm10') else "—"
    pm25_str = f"{aq.get('pm25', 0):.1f}" if aq.get('pm25') else "—"

    table_data.append({
        'Site ID': site_id,
        'Site Name': result.get('site_name', '?'),
        'IP Address': result.get('ip', '?'),
        'Urgency': result.get('urgency', '?'),
        'RUL (days)': f"{rul:.0f}" if rul is not None else "?",
        'Episodes': result.get('episodes_count', '?'),
        'R²': f"{result.get('r2', 0):.3f}",
        'Current ΔT (°C)': f"{result.get('current_dt', 0):.1f}",
        'Failure ΔT (°C)': f"{result.get('failure_dt', 0):.1f}",
        'Filter Life Used': f"{result.get('pct_life', 0):.0f}%",
        'PM10 (μg/m³)': pm10_str,
        'PM2.5 (μg/m³)': pm25_str,
        'Pollution Effect': pollution_indicator,
        '_rul_raw': rul if rul is not None else float('inf'),
        '_urgency_rank': {'URGENT': 0, 'WARNING': 1, 'OK': 2, 'UNKNOWN': 3}.get(result.get('urgency'), 4),
    })

if not table_data:
    st.warning("No sites match filter criteria.")
else:
    df = pd.DataFrame(table_data)

    if sort_by == 'RUL (ascending)':
        df = df.sort_values('_rul_raw')
    elif sort_by == 'Site Name (A-Z)':
        df = df.sort_values('Site Name')
    elif sort_by == 'Urgency + RUL':
        df = df.sort_values(['_urgency_rank', '_rul_raw'])

    df = df.drop(columns=['_rul_raw', '_urgency_rank'])
    st.dataframe(df, use_container_width=True, hide_index=True)

st.markdown("---")

# ============================================================================
# EXPANDABLE SITE DETAILS
# ============================================================================

st.markdown(f'<h3 style="color: #1a202c; margin-top: 1.5rem; margin-bottom: 1rem; font-weight: 700;">📈 Site Details & Trend Analysis</h3>', unsafe_allow_html=True)

detail_sites = []
csv_sites = []  # Separate list for CSV sites to ensure they're always shown

for site_id, result in sorted(sites_recalc.items()):
    # Check if it's a CSV site with filter change
    is_csv_site = result.get('data_source') == 'csv'
    has_filter_change_metadata = result.get('filter_change') is not None

    if is_csv_site and has_filter_change_metadata:
        # CSV sites always go to a separate list (ensure they're displayed)
        search_str = f"{site_id} {result.get('site_name', '')}".lower()
        if not (search_term.lower() and search_term.lower() not in search_str):
            csv_sites.append((site_id, result))
        continue

    # Show successful sites (check urgency filter)
    is_successful = result.get('success')
    if not is_successful:
        continue

    if result.get('urgency') not in urgency_filter:
        continue

    search_str = f"{site_id} {result.get('site_name', '')}".lower()
    if search_term.lower() and search_term.lower() not in search_str:
        continue

    detail_sites.append((site_id, result))

# Combine CSV sites first, then successful sites
detail_sites = csv_sites + detail_sites

detail_sites = detail_sites[:20]

if not detail_sites:
    st.info("No sites to display. Adjust filters to see site details.")
else:
    for site_id, result in detail_sites:
        urgency = result.get('urgency', '?')
        rul = result.get('rul_days', '?')
        equation = get_model_equation(result)
        color_map = {'URGENT': '🔴', 'WARNING': '🟡', 'OK': '🟢', 'UNKNOWN': '⚪'}
        emoji = color_map.get(urgency, '❓')

        # For CSV sites without RUL, show filter change status instead
        if result.get('data_source') == 'csv' and not result.get('success'):
            if result.get('filter_change_detected'):
                rul_str = "📊 Filter Change Detected"
                emoji = "📊"
            else:
                rul_str = "⚠️ Insufficient Data"
                emoji = "⚠️"
        else:
            rul_str = f"{rul:.0f}d" if isinstance(rul, float) else str(rul)

        expander_label = f"{emoji} {site_id} — {result.get('site_name', '?')} ({rul_str})"

        # Pre-format values for site details
        slope_val = f"{result.get('slope', 0):.4f}" if isinstance(result.get('slope'), (int, float)) else '?'
        avg_hrs_val = f"{result.get('avg_adjusted_hours_per_day', 0):.2f}" if isinstance(result.get('avg_adjusted_hours_per_day'), (int, float)) else '?'
        
        current_dt_val = f"{result.get('current_dt', 0):.1f}" if isinstance(result.get('current_dt'), (int, float)) else '?'
        failure_dt_val = f"{result.get('failure_dt', 0):.1f}" if isinstance(result.get('failure_dt'), (int, float)) else '?'
        baseline_dt_val = f"{result.get('baseline_dt', 0):.1f}" if isinstance(result.get('baseline_dt'), (int, float)) else '?'

        # Pre-format air quality values (handle None values)
        aq = result.get('air_quality') or {}
        pm25_val = f"{aq.get('pm25', 0):.1f}" if isinstance(aq.get('pm25'), (int, float)) else '?'
        pm10_val = f"{aq.get('pm10', 0):.1f}" if isinstance(aq.get('pm10'), (int, float)) else '?'
        has_air_quality = result.get('air_quality') is not None

        air_quality_html = ""
        if has_air_quality:
            pollution_blurb = calculate_pollution_impact_blurb(result, data)
            blurb_html = f"<div style='margin-top: 12px; padding: 10px; background: #f0fdf4; border-radius: 4px; font-size: 0.85rem; color: #374151; line-height: 1.6;'>{pollution_blurb.replace(chr(10), '<br>')}</div>" if pollution_blurb else ""
            air_quality_html = f"""<div style='background: #ecfdf5; padding: 14px; border-radius: 8px; border-left: 4px solid #059669;'><strong style='font-size: 0.9rem; color: #1a202c; text-transform: uppercase; letter-spacing: 0.05em;'>🌍 Air Quality (90-day avg)</strong><br><div style='margin-top: 8px; font-size: 0.85rem; color: #374151;'><div>PM2.5: <strong style='font-size: 1.1em; color: #1a202c;'>{pm25_val} μg/m³</strong></div><div>PM10: <strong style='font-size: 1.1em; color: #1a202c;'>{pm10_val} μg/m³</strong></div>{blurb_html}</div></div>"""

        # Track expander state in session
        expand_key = f"expand_{site_id}"
        is_expanded = st.session_state.get(expand_key, False)

        with st.expander(expander_label, expanded=is_expanded):
            col1, col2 = st.columns([1, 2])

            with col1:
                # Check if site has insufficient data (negative slope)
                has_insufficient_data = result.get('slope', 0) <= 0

                st.markdown(f"""
<div style="color: #1a202c; line-height: 2.0; white-space: normal; word-wrap: break-word; font-size: 0.95rem;">

<div style="background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid
#4f7cff;">
<strong style="font-size: 0.9rem; color: #1a202c; text-transform: uppercase; letter-spacing: 0.05em;">📍 Site
Info</strong><br>
<div style="margin-top: 8px; font-size: 0.85rem; color: #374151;">
<div>IP Address: <code style="background: #ffffff; padding: 2px 6px; border-radius: 4px; color:
#4f7cff;">{result.get('ip')}</code></div>
<div>Episodes Counted: <strong>{result.get('episodes_count')}</strong></div>
</div>
</div>"""
                , unsafe_allow_html=True)

                if has_insufficient_data:
                    st.markdown(f"""
<div style="background: #fef2f2; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #dc2626;">
<strong style="font-size: 0.9rem; color: #991b1b; text-transform: uppercase; letter-spacing: 0.05em;">⚠️ Data Insufficient for Analysis</strong><br>
<div style="margin-top: 8px; font-size: 0.85rem; color: #374151;">
<div>No clear degradation trend detected. Filter may be new, recently replaced, or experiencing variable conditions. Unable to project RUL or trend analysis.</div>
</div>
</div>

{air_quality_html}

</div>
""", unsafe_allow_html=True)
                else:
                    st.markdown(f"""
<div style="background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid
#4f7cff;">
<div style="font-size: 0.85rem; color: #374151;">
<div>Urgency: <strong style="color: {'#ef4444' if urgency == 'URGENT' else '#f59e0b' if urgency == 'WARNING' else
'#10b981' if urgency == 'OK' else '#6b7280'};">{urgency}</strong></div>
</div>
</div>

<div style="background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid
#8b5cf6;">
<strong style="font-size: 0.9rem; color: #1a202c; text-transform: uppercase; letter-spacing: 0.05em;">🔬 Model
Configuration</strong><br>
<div style="margin-top: 8px; font-size: 0.85rem; color: #374151;">
<div style="margin-top: 6px; font-family: monospace; background: #ffffff; padding: 8px; border-radius: 4px; font-size:
0.8rem; color: #4f7cff; word-break: break-all;">{equation}</div>
<div style="margin-top: 6px;">Air Quality: <span style="background: {'#dcfce7' if result.get('air_quality') else
'#f3f4f6'}; color: {'#166534' if result.get('air_quality') else '#6b7280'}; padding: 2px 8px; border-radius: 4px;
font-weight: 600; font-size: 0.8rem;">{"✓ Available" if result.get('air_quality') else "✗ Unavailable"}</span></div>
<div style="margin-top: 6px;">Pollution Effect: <span style="background: {'#fce7f3' if result.get('pollution_effect') else
'#f3f4f6'}; color: {'#831843' if result.get('pollution_effect') else '#6b7280'}; padding: 2px 8px; border-radius: 4px;
font-weight: 600; font-size: 0.8rem;">{"✓ Applied" if result.get('pollution_effect') is not None else "✗ Not applied"}</span></div>
</div>
</div>

<div style="background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid
#ec4899;">
<strong style="font-size: 0.9rem; color: #1a202c; text-transform: uppercase; letter-spacing: 0.05em;">📈 Trend
Analysis</strong><br>
<div style="margin-top: 8px; font-size: 0.85rem; color: #374151;">
<div>Fit Quality (R²): <strong style="font-size: 1.1em; color: #1a202c;">{f"{result.get('r2', 0):.3f}" if isinstance(result.get('r2'), (int, float)) else '?'}</strong> <span
style="color: #6b7280;">({('Excellent' if float(result.get('r2', 0)) > 0.7 else 'Good' if float(result.get('r2', 0)) >
0.5 else 'Fair' if float(result.get('r2', 0)) > 0.25 else 'Poor')})</span></div>
<div>Degradation Rate: <strong style="font-size: 1.1em; color: #ef4444;">{f"{result.get('slope', 0):.3f}" if isinstance(result.get('slope'), (int, float)) else '?'}°C</strong>/episode</div>
</div>
</div>

<div style="background: #fef2f2; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #dc2626;">
<strong style="font-size: 0.9rem; color: #991b1b; text-transform: uppercase; letter-spacing: 0.05em;">⏱️ RUL Estimate</strong><br>
<div style="margin-top: 8px; font-size: 0.85rem; color: #374151;">
<div>Slope: <strong style="font-size: 1.1em; color: #1a202c;">{slope_val}°C/hr</strong></div>
<div>Avg Adjusted Hours/Day: <strong style="font-size: 1.1em; color: #1a202c;">{avg_hrs_val}</strong></div>
<div style="margin-top: 6px;">Days Until Replacement: <strong style="font-size: 1.2em; color: #dc2626;">{rul_str}</strong></div>
<div>Filter Life Used: <strong style="font-size: 1.1em; color: #1a202c;">{f"{result.get('pct_life', 0):.0f}" if isinstance(result.get('pct_life'), (int, float)) else '?'}%</strong></div>
</div>
</div>

<div style="background: #f0f9ff; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #0284c7;">
<strong style="font-size: 0.9rem; color: #1a202c; text-transform: uppercase; letter-spacing: 0.05em;">🌡️  Temperature
Readings</strong><br>
<div style="margin-top: 8px; font-size: 0.85rem; color: #374151;">
<div>Current ΔT: <strong style="font-size: 1.1em; color: #1a202c;">{current_dt_val}°C</strong></div>
<div>Failure Threshold: <strong style="font-size: 1.1em; color: #ef4444;">{failure_dt_val}°C</strong></div>
<div>Baseline ΔT: <span style="color: #6b7280;">{baseline_dt_val}°C</span></div>
</div>
</div>

{air_quality_html}

</div>
""", unsafe_allow_html=True)

            # Filter change detection UI
            if result.get('filter_change_detected'):
                st.markdown("---")
                fc = result['filter_change_detected']
                st.info(f"⚠️ **Possible filter change detected** at {fc['hours']:.0f} hours (drop: {fc['drop']:.1f}°C from {fc['before_dt']:.1f}°C to {fc['after_dt']:.1f}°C)")

                col_fc1, col_fc2 = st.columns([1, 1])
                with col_fc1:
                    session_key = f"fc_confirm_{site_id}"
                    expand_key = f"expand_{site_id}"
                    hours_key = f"fc_hours_{site_id}"
                    fc_hours_value = fc['hours']

                    # Use default params to capture variables properly in closure
                    def on_checkbox_change(sid=site_id, hk=hours_key, fh=fc_hours_value, ek=expand_key):
                        st.session_state[hk] = fh
                        st.session_state[ek] = True  # Keep expander open

                    confirmed = st.checkbox(
                        f"Confirm filter change at this site",
                        value=st.session_state.get(session_key, False),
                        key=session_key,
                        on_change=on_checkbox_change
                    )

                with col_fc2:
                    if st.session_state.get(session_key, False):
                        adjust_key = f"fc_adjust_{site_id}"
                        expand_key = f"expand_{site_id}"
                        hours_key = f"fc_hours_{site_id}"

                        # Use default params to capture variables properly in closure
                        def on_hours_change(hk=hours_key, ak=adjust_key, ek=expand_key):
                            st.session_state[hk] = st.session_state.get(ak, st.session_state.get(hk))
                            st.session_state[ek] = True  # Keep expander open

                        adjusted_hours = st.number_input(
                            f"Adjust hours",
                            value=st.session_state.get(hours_key, fc['hours']),
                            step=10.0,
                            key=adjust_key,
                            on_change=on_hours_change
                        )
                        st.caption(f"Edit the time to specify when the filter was changed and click Enter — Current: {adjusted_hours:.0f} hours")

            else:
                # Manual filter change option (no detected change)
                st.markdown("---")
                st.markdown("**Was the filter changed at this site?**")

                col_fc1, col_fc2 = st.columns([1, 1])
                with col_fc1:
                    session_key = f"fc_confirm_{site_id}"
                    expand_key = f"expand_{site_id}"
                    hours_key = f"fc_hours_{site_id}"

                    def on_manual_checkbox_change(ek=expand_key):
                        st.session_state[ek] = True  # Keep expander open

                    manual_confirm = st.checkbox(
                        f"Yes, filter was changed",
                        value=st.session_state.get(session_key, False),
                        key=session_key,
                        on_change=on_manual_checkbox_change
                    )

                with col_fc2:
                    if st.session_state.get(session_key, False):
                        adjust_key = f"fc_adjust_{site_id}"
                        expand_key = f"expand_{site_id}"

                        def on_manual_hours_change(hk=hours_key, ek=expand_key, ak=adjust_key):
                            # Set hours from the input value and keep expander open
                            manual_val = st.session_state.get(ak, 0.0)
                            if manual_val > 0:
                                st.session_state[hk] = manual_val
                            st.session_state[ek] = True  # Keep expander open

                        manual_hours = st.number_input(
                            f"Filter changed at (hours)",
                            value=st.session_state.get(hours_key, 0.0),
                            step=10.0,
                            key=adjust_key,
                            on_change=on_manual_hours_change
                        )
                        # Display confirmation
                        if manual_hours > 0:
                            st.caption(f"Enter the hours when filter was changed and click Enter — Current: {manual_hours:.0f} hours")
                        else:
                            st.caption("Enter the hours when filter was changed and click Enter")

            with col2:
                # Show trend plot for all sites (helps users identify filter changes)
                max_deltas = result.get('max_deltas', [])
                cumul_hours = result.get('cumulative_adjusted_hours', [])
                episode_start_times = result.get('episode_start_times', [])

                if len(max_deltas) > 2 and len(cumul_hours) == len(max_deltas):
                    fig = go.Figure()

                    # Extract dates from episode_start_times for display in hover
                    episode_dates = []
                    if episode_start_times and len(episode_start_times) == len(max_deltas):
                        for ts in episode_start_times:
                            try:
                                # Parse ISO format timestamp and format as "MMM DD"
                                dt = datetime.fromisoformat(ts.replace('Z', '+00:00'))
                                episode_dates.append(dt.strftime('%b %d'))
                            except:
                                episode_dates.append('N/A')
                    else:
                        episode_dates = ['N/A'] * len(max_deltas)

                    fig.add_trace(go.Scatter(
                        x=cumul_hours, y=max_deltas,
                        mode='markers',
                        marker=dict(size=6, color='#a5b4fc', opacity=0.7),
                        name='Max ΔT per episode',
                        customdata=episode_dates,
                        hovertemplate='<b>%{customdata}</b><br>Cumulative Adjusted Hours: %{x:.1f}<br>Max ΔT: %{y:.2f}°C<extra></extra>'
                    ))

                    fig.add_hline(
                        y=result.get('failure_dt', 10.0),
                        line_dash='dot',
                        line_color='#ef4444',
                        annotation_text=f"Failure: {result.get('failure_dt', 10.0):.1f}°C",
                        annotation_position='right'
                    )

                    if len(cumul_hours) >= 2 and result.get('slope', 0) > 0:
                        r2 = result.get('r2', 0)
                        slope = result.get('slope', 0)
                        intercept = result.get('intercept_recalc', result.get('intercept', 0))

                        # X-axis from 0 to max hours
                        max_hours = max(cumul_hours) if cumul_hours else 100
                        x_axis = np.linspace(0, max_hours, 100)

                        # Check if dual trend (filter change split) should be shown
                        if result.get('dual_trend'):
                            dual = result['dual_trend']
                            split_h = dual['split_hours']

                            # Pre-change trend line
                            if dual['pre_split_coeffs']:
                                pre_coeffs = dual['pre_split_coeffs']
                                pre_x = [x for x in x_axis if x < split_h]
                                if len(pre_x) >= 2:
                                    pre_trend = [pre_coeffs[1] + pre_coeffs[0] * x for x in pre_x]
                                    fig.add_trace(go.Scatter(
                                        x=pre_x, y=pre_trend,
                                        mode='lines',
                                        line=dict(color='#f59e0b', width=2, dash='dash'),
                                        name='Pre-change trend',
                                        hovertemplate='Cumulative Adjusted Hours: %{x:.1f}<br>Trend: %{y:.2f}°C<extra></extra>'
                                    ))

                            # Post-change trend line
                            post_coeffs = dual['post_split_coeffs']
                            post_x = [x for x in x_axis if x >= split_h]
                            if len(post_x) >= 2:
                                post_trend = [post_coeffs[1] + post_coeffs[0] * x for x in post_x]
                                fig.add_trace(go.Scatter(
                                    x=post_x, y=post_trend,
                                    mode='lines',
                                    line=dict(color='#10b981', width=2.5, dash='dash'),
                                    name=f'Post-change trend (R²={r2:.3f})',
                                    hovertemplate='Cumulative Adjusted Hours: %{x:.1f}<br>Trend: %{y:.2f}°C<extra></extra>'
                                ))

                            # Add vertical line at filter change
                            fig.add_vline(x=split_h, line_dash="dot", line_color="#666", annotation_text="Filter changed", annotation_position="bottom")
                        else:
                            # Single trend line from x=0
                            trend_line = [intercept + slope * x for x in x_axis]
                            fig.add_trace(go.Scatter(
                                x=x_axis, y=trend_line,
                                mode='lines',
                                line=dict(color='#4f7cff', width=2, dash='dash'),
                                name=f'Trend (R²={r2:.3f})',
                                hovertemplate='Cumulative Adjusted Hours: %{x:.1f}<br>Trend: %{y:.2f}°C<extra></extra>'
                            ))

                    fig.update_layout(
                        title=dict(
                            text=f"ΔT Trend — {site_id}",
                            font=dict(size=14, color='#1a202c', family='Arial, sans-serif'),
                            x=0.5,
                            xanchor='center'
                        ),
                        xaxis=dict(
                            title='Cumulative Adjusted Fan Hours',
                            title_font=dict(size=12, color='#1a202c'),
                            tickfont=dict(size=10, color='#1a202c'),
                            showgrid=True,
                            gridwidth=1,
                            gridcolor='#e5e7eb',
                        ),
                        yaxis=dict(
                            title='ΔT (°C)',
                            title_font=dict(size=12, color='#1a202c'),
                            tickfont=dict(size=10, color='#1a202c'),
                            showgrid=True,
                            gridwidth=1,
                            gridcolor='#e5e7eb',
                        ),
                        height=380,
                        hovermode='x unified',
                        paper_bgcolor='#ffffff',
                        plot_bgcolor='#fafbfc',
                        margin=dict(l=70, r=70, t=60, b=60),
                        font=dict(family='Arial, sans-serif', size=10, color='#1a202c'),
                        showlegend=True,
                        legend=dict(
                            x=0.02,
                            y=0.98,
                            bgcolor='rgba(255,255,255,0.9)',
                            bordercolor='#cbd5e1',
                            borderwidth=1,
                            font=dict(size=10, color='#1a202c')
                        ),
                    )

                    st.plotly_chart(fig, use_container_width=True, config={'displayModeBar': False})
                else:
                    st.info("Not enough episodes for trend plot.")

st.markdown("---")
st.markdown(f"""
<div style="text-align:center;font-size:0.75rem;color:#6b7280;margin-top:2rem;padding:1.5rem;background:#f8fafc;border-radius:8px;border:1px solid #e5e7eb;">
  <strong style="color: #1a202c;">Last Updated</strong> {data.get('query_timestamp', 'unknown')}<br>
  <span style="color: #4b5563;">Query Time: {f"{data.get('query_elapsed_seconds', 0):.1f}" if isinstance(data.get('query_elapsed_seconds'), (int, float)) else '?'}s for {data.get('sites_queried', '?')} sites</span><br>
  <span style="color: #9ca3af; font-size: 0.7rem;">Dashboard: Mode 3 Rolling Median RUL Analysis</span>
</div>
""", unsafe_allow_html=True)
