#!/usr/bin/env python3
"""
Unified RUL Dashboard for 1020+ Rogers HVAC Sites.
Displays Mode 3 (rolling median) analysis only.
Reads from sites_data.json (generated by query_sites.py).
"""

import json
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime
from pathlib import Path

# Must be the first Streamlit command
st.set_page_config(
    page_title="Rogers HVAC RUL Dashboard",
    page_icon="🌡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# CSS STYLING
# ============================================================================
st.markdown("""
<style>
    /* Main app background */
    .stApp { background-color: #ffffff; }

    /* Hide default elements EXCEPT header (header contains the sidebar toggle!) */
    #MainMenu, footer { visibility: hidden; }

    /* Sidebar styling */
    [data-testid="stSidebar"] { background-color: #1e3a5f; }
    [data-testid="stSidebar"] .stMarkdown,
    [data-testid="stSidebar"] .stMarkdown * { color: #ffffff !important; }
    [data-testid="stSidebar"] label { color: #e0e7ff !important; font-weight: 500 !important; }
    
    [data-testid="stSidebar"] .stSelectbox label {
        font-size: 0.78rem !important;
        letter-spacing: 0.08em !important;
        text-transform: uppercase !important;
        font-weight: 600 !important;
    }
    
    /* Sidebar Input fields */
    [data-testid="stSidebar"] input,
    [data-testid="stSidebar"] .stSelectbox div,
    [data-testid="stSidebar"] .stRadio span,
    [data-testid="stSidebar"] .stSlider {
        color: #ffffff !important;
    }
    
    [data-testid="stSidebar"] input {
        background-color: #2d4a7a !important;
        border-color: #4f7cff !important;
    }
    
    [data-testid="stSidebar"] input::placeholder { color: #a5b4fc !important; }

    /* Main content text */
    body, .stApp, main, [role="main"], .stMarkdown *,
    .stMarkdown p, h1, h2, h3, h4, h5, h6 {
        color: #1a202c !important;
    }

    /* Metric cards */
    .metric-card {
        background: #ffffff;
        border-radius: 12px;
        padding: 20px 24px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        border-left: 5px solid #4f7cff;
        min-height: 95px;
        box-sizing: border-box;
    }
    .metric-card.warn { border-left-color: #f59e0b; }
    .metric-card.danger { border-left-color: #ef4444; }
    .metric-card .label {
        font-size: 0.7rem;
        color: #6b7280 !important;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        margin-bottom: 8px;
        font-weight: 700;
    }
    .metric-card .value {
        font-size: 1.8rem;
        font-weight: 800;
    }
    .metric-card .sub {
        font-size: 0.75rem;
        color: #6b7280 !important;
        margin-top: 4px;
        font-weight: 500;
    }

    /* Expanders and containers - Fixed active/focus black background */
    [data-testid="stExpander"] {
        background-color: #ffffff !important;
        border: 1px solid #e5e7eb !important;
        border-radius: 8px !important;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05) !important;
    }
    
    [data-testid="stExpander"] details summary,
    [data-testid="stExpander"] details summary:hover,
    [data-testid="stExpander"] details summary:active,
    [data-testid="stExpander"] details summary:focus {
        background-color: #ffffff !important;
        color: #1a202c !important;
    }

    [data-testid="stExpanderDetails"] {
        background-color: #fafbfc !important;
    }

    /* Alerts / Info Boxes */
    .stInfo, .stWarning, .stSuccess, .stError {
        border-radius: 8px !important;
        background-color: #f0f9ff !important;
    }
    .stInfo { border-left: 4px solid #4f7cff !important; }
    .stWarning { border-left: 4px solid #f59e0b !important; }
    .stSuccess { border-left: 4px solid #10b981 !important; }
    .stError { border-left: 4px solid #ef4444 !important; }

    /* Tables & Plotly */
    [data-testid="stDataFrame"] { background-color: #ffffff !important; }
    .js-plotly-plot { margin: 1.5rem 0; }
    a { color: #4f7cff !important; text-decoration: none !important; }
    a:hover { text-decoration: underline !important; }

    /* Main block spacing */
    .block-container {
        padding-top: 2rem !important;
        padding-left: 2rem !important;
        padding-right: 2rem !important;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================
@st.cache_data(ttl=300)
def load_sites_data(json_file='sites_data.json'):
    """Load aggregated site data from JSON."""
    if not Path(json_file).exists():
        st.error(f"Data file not found: {json_file}")
        st.info("Run `python3 query_sites.py` on the Bell laptop to generate this file.")
        st.stop()
    with open(json_file) as f:
        return json.load(f)

def recalculate_rul(site_result, new_failure_dt):
    """Recalculate RUL for a site using a custom failure ΔT threshold."""
    site_copy = site_result.copy()
    if not site_result.get('success'):
        return site_copy

    current_dt = site_result.get('current_dt', 0)
    slope = site_result.get('slope', 0)
    r2 = site_result.get('r2', 0)
    baseline_dt = site_result.get('baseline_dt', 0)
    intercept = site_result.get('intercept', 0)

    if current_dt <= 0 or slope <= 0:
        site_copy['rul_days'] = None
        site_copy['urgency'] = site_result.get('urgency', 'UNKNOWN')
        return site_copy

    site_copy['failure_dt'] = new_failure_dt

    if current_dt >= new_failure_dt:
        site_copy.update({'rul_days': 0, 'urgency': 'URGENT', 'pct_life': 100})
        return site_copy

    if r2 < 0.25:
        site_copy.update({'rul_days': 999, 'urgency': 'OK', 'pct_life': 0})
        return site_copy

    avg_hours_per_day = site_result.get('avg_adjusted_hours_per_day', 1.0)
    hours_to_failure = (new_failure_dt - intercept) / slope if slope > 0 else 999
    remaining_hours = hours_to_failure - site_result.get('total_adjusted_hours', 0)
    rul_days = max(0, remaining_hours / avg_hours_per_day if avg_hours_per_day > 0 else 999)
    
    site_copy['rul_days'] = rul_days
    if baseline_dt > 0:
        site_copy['pct_life'] = max(0, min(100, (current_dt - baseline_dt) / (new_failure_dt - baseline_dt) * 100))

    if rul_days < 14:
        site_copy['urgency'] = 'URGENT'
    elif rul_days < 30:
        site_copy['urgency'] = 'WARNING'
    else:
        site_copy['urgency'] = 'OK'

    return site_copy

def calculate_pollution_impact_blurb(site_result, all_sites_data):
    """Calculate how this site's pollution compares to the site average."""
    if not site_result.get('air_quality'): return None

    regression = all_sites_data.get('air_quality_regression', {})
    beta_pm25 = regression.get('coefficient_pm25') or 0
    beta_pm10 = regression.get('coefficient_pm10') or 0

    pm25_values, pm10_values = [], []
    for result_item in all_sites_data.get('sites', {}).values():
        if aq := result_item.get('air_quality'):
            if aq.get('pm25') is not None: pm25_values.append(aq['pm25'])
            if aq.get('pm10') is not None: pm10_values.append(aq['pm10'])

    site_pm25 = site_result['air_quality'].get('pm25')
    site_pm10 = site_result['air_quality'].get('pm10')

    if not pm25_values or not pm10_values or site_pm25 is None or site_pm10 is None:
        return None

    avg_pm25, avg_pm10 = np.mean(pm25_values), np.mean(pm10_values)
    slope_impact = (beta_pm25 * (site_pm25 - avg_pm25)) + (beta_pm10 * (site_pm10 - avg_pm10))
    raw_slope = site_result.get('slope', 0.001)
    
    if raw_slope <= 0: return None

    rul_impact_days = (slope_impact / raw_slope) * 30 # Approx 30 day avg RUL
    direction = "faster" if rul_impact_days < 0 else "slower"

    return (f"**Pollution Impact (vs Site Average):**\n"
            f"- PM2.5: {site_pm25:.1f} μg/m³ ({site_pm25 - avg_pm25:+.1f} vs avg {avg_pm25:.1f})\n"
            f"- PM10: {site_pm10:.1f} μg/m³ ({site_pm10 - avg_pm10:+.1f} vs avg {avg_pm10:.1f})\n\n"
            f"Based on air quality patterns, this location's air quality causes the filter to degrade **{abs(rul_impact_days):.1f} days {direction}** than typical.")

def get_model_type_and_equation(result):
    intercept, slope = result.get('intercept', 0), result.get('slope', 0)
    return "1-Factor", f"ΔT = {intercept:.2f} + {slope:.4f} × (adj_hours)"

# ============================================================================
# DATA & SIDEBAR
# ============================================================================
data = load_sites_data()
sites = data['sites']

with st.sidebar:
    st.markdown("### ⚙️ Analysis Controls", help="Adjust these parameters to recalculate RUL")
    min_duration = st.slider("Min episode duration (min)", 10, 120, 30, step=5)
    fan_threshold = st.slider("Min fan speed (%)", 80, 100, 95, step=1)
    rolling_window = st.slider("Rolling median window (episodes)", 3, 10, 5, step=1)
    failure_dt = st.slider("ΔT at filter failure (°C)", 5.0, 20.0, 10.0, step=0.5)

    st.markdown("---")
    st.markdown("### 🔍 Filter & Sort Options")
    urgency_filter = st.multiselect(
        "Urgency Level",
        ['URGENT', 'WARNING', 'OK', 'UNKNOWN'],
        default=['URGENT', 'WARNING', 'OK']
    )
    search_term = st.text_input("Search site name/ID", "").lower()
    sort_by = st.radio(
        "Sort by",
        ['RUL (ascending)', 'Site Name (A-Z)', 'Urgency + RUL']
    )

# ============================================================================
# MAIN CONTENT HEADER
# ============================================================================
st.markdown("<h1 style='margin-bottom: 0.5rem;'>🌡️ Rogers HVAC Filter RUL Dashboard</h1>", unsafe_allow_html=True)

st.markdown("""
<div style="background-color: #f8fafc; padding: 18px 24px; border-radius: 8px; border-left: 4px solid #4f7cff; margin-bottom: 24px; color: #374151; font-size: 0.95rem; line-height: 1.6; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
    <strong style="color: #1a202c; font-size: 1.05rem;">About This Dashboard</strong><br>
    This tool predicts the Remaining Useful Life (RUL) of HVAC filters across 1020+ sites. It tracks the maximum temperature differential (ΔT) during free cooling events (when fans run at ≥95% speed for at least 30 minutes). Because air resistance scales with fan speed squared, operating hours are adjusted proportionately to model how the filter degrades over time. 
    <br><br>
    The system fits a linear degradation trend to predict when a filter's ΔT will exceed a critical failure threshold (default 10°C). For sites with local air quality data (PM2.5/PM10), the model analyzes if local pollution levels are speeding up or slowing down the filter degradation relative to the network average.
</div>
""", unsafe_allow_html=True)

# ============================================================================
# DATA PROCESSING (RECALCULATE, FILTER, SORT IN ONE PASS)
# ============================================================================
sites_recalc = {site_id: recalculate_rul(res, failure_dt) for site_id, res in sites.items()}
successful_sites = [s for s in sites_recalc.values() if s.get('success')]

# Single unified filter and sort list for performance
filtered_site_tuples = []
for site_id, result in sites_recalc.items():
    if not result.get('success'): continue
    if result.get('urgency') not in urgency_filter: continue
    if search_term and search_term not in f"{site_id} {result.get('site_name', '')}".lower(): continue
    
    # Pre-calculate sorting keys
    rul = result.get('rul_days', float('inf'))
    if rul is None: rul = float('inf')
    rank = {'URGENT': 0, 'WARNING': 1, 'OK': 2, 'UNKNOWN': 3}.get(result.get('urgency'), 4)
    
    filtered_site_tuples.append((site_id, result, rul, rank))

# Sort the master list based on user selection
if sort_by == 'RUL (ascending)':
    filtered_site_tuples.sort(key=lambda x: x[2])
elif sort_by == 'Site Name (A-Z)':
    filtered_site_tuples.sort(key=lambda x: x[1].get('site_name', ''))
elif sort_by == 'Urgency + RUL':
    filtered_site_tuples.sort(key=lambda x: (x[3], x[2]))

st.markdown(f"<h2 style='margin-bottom: 1.5rem;'>Status — {len(successful_sites)} Sites Analyzed</h2>", unsafe_allow_html=True)

# Metric totals (Global based on recalculated sites, not filtered list)
col1, col2, col3, col4, col5 = st.columns(5)
with col1: st.markdown(f'<div class="metric-card danger"><div class="label">🔴 URGENT</div><div class="value">{sum(1 for s in successful_sites if s.get("urgency") == "URGENT")}</div><div class="sub">< 14 days</div></div>', unsafe_allow_html=True)
with col2: st.markdown(f'<div class="metric-card warn"><div class="label">🟡 WARNING</div><div class="value">{sum(1 for s in successful_sites if s.get("urgency") == "WARNING")}</div><div class="sub">14–30 days</div></div>', unsafe_allow_html=True)
with col3: st.markdown(f'<div class="metric-card"><div class="label">🟢 OK</div><div class="value">{sum(1 for s in successful_sites if s.get("urgency") == "OK")}</div><div class="sub">≥ 30 days</div></div>', unsafe_allow_html=True)
with col4: st.markdown(f'<div class="metric-card"><div class="label">⚪ FAILED</div><div class="value">{len(sites) - len(successful_sites)}</div><div class="sub">Query error</div></div>', unsafe_allow_html=True)
with col5:
    valid_ruls = [s['rul_days'] for s in successful_sites if isinstance(s.get('rul_days'), (int, float))]
    avg_rul_str = f"{np.mean(valid_ruls):.0f}d" if valid_ruls else "?"
    st.markdown(f'<div class="metric-card"><div class="label">Average RUL</div><div class="value">{avg_rul_str}</div><div class="sub">All sites</div></div>', unsafe_allow_html=True)

st.markdown("---")

# ============================================================================
# DATAFRAME GENERATION
# ============================================================================
st.markdown(f'<h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">📊 Sites Status Table</h3>', unsafe_allow_html=True)

if not filtered_site_tuples:
    st.warning("No sites match filter criteria.")
else:
    table_data = []
    for site_id, result, _, _ in filtered_site_tuples:
        rul = result.get('rul_days')
        model_type, _ = get_model_type_and_equation(result)
        aq = result.get('air_quality', {})
        
        table_data.append({
            'Site ID': site_id,
            'Site Name': result.get('site_name', '?'),
            'IP Address': result.get('ip', '?'),
            'Model': model_type,
            'Urgency': result.get('urgency', '?'),
            'RUL (days)': f"{rul:.0f}" if rul is not None else "?",
            'Episodes': result.get('episodes_count', '?'),
            'R²': f"{result.get('r2', 0):.3f}",
            'Current ΔT (°C)': f"{result.get('current_dt', 0):.1f}",
            'Failure ΔT (°C)': f"{result.get('failure_dt', 0):.1f}",
            'Filter Life Used': f"{result.get('pct_life', 0):.0f}%",
            'PM10 (μg/m³)': f"{aq.get('pm10', 0):.1f}" if aq.get('pm10') else "—",
            'PM2.5 (μg/m³)': f"{aq.get('pm25', 0):.1f}" if aq.get('pm25') else "—",
            'Pollution Effect': f"({result.get('pollution_effect'):+.3f})" if result.get('pollution_effect') is not None else "—"
        })
    st.dataframe(pd.DataFrame(table_data), use_container_width=True, hide_index=True)

st.markdown("---")

# ============================================================================
# EXPANDABLE DETAILS
# ============================================================================
st.markdown(f'<h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">📈 Site Details & Trend Analysis</h3>', unsafe_allow_html=True)

top_details = filtered_site_tuples[:20]

if not top_details:
    st.info("No sites to display. Adjust filters to see site details.")
else:
    for site_id, result, _, _ in top_details:
        urgency = result.get('urgency', '?')
        rul = result.get('rul_days', '?')
        model_type, equation = get_model_type_and_equation(result)
        emoji = {'URGENT': '🔴', 'WARNING': '🟡', 'OK': '🟢', 'UNKNOWN': '⚪'}.get(urgency, '❓')
        rul_str = f"{rul:.0f}d" if isinstance(rul, (int, float)) else str(rul)
        
        with st.expander(f"{emoji} {site_id} — {result.get('site_name', '?')} [{model_type}] (RUL: {rul_str})"):
            col1, col2 = st.columns([1, 2])
            
            with col1:
                aq = result.get('air_quality', {})
                air_quality_html = ""
                if aq:
                    blurb = calculate_pollution_impact_blurb(result, data)
                    blurb_html = f"<div style='margin-top: 12px; padding: 10px; background: #f0fdf4; border-radius: 4px; font-size: 0.85rem; color: #374151;'>{blurb.replace(chr(10), '<br>')}</div>" if blurb else ""
                    air_quality_html = f"""
                    <div style='background: #ecfdf5; padding: 14px; border-radius: 8px; border-left: 4px solid #059669;'>
                        <strong>🌍 Air Quality (90-day avg)</strong><br>
                        PM2.5: <strong>{aq.get('pm25', 0):.1f} μg/m³</strong> | PM10: <strong>{aq.get('pm10', 0):.1f} μg/m³</strong>
                        {blurb_html}
                    </div>"""

                st.markdown(f"""
                <div style="line-height: 2.0; font-size: 0.95rem;">
                    <div style="background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #4f7cff;">
                        <strong>📍 Site Info</strong><br>
                        IP: <code>{result.get('ip')}</code> | Urgency: <strong>{urgency}</strong> | Episodes: <strong>{result.get('episodes_count')}</strong>
                    </div>
                    <div style="background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #8b5cf6;">
                        <strong>🔬 Model Configuration</strong><br>
                        <div style="font-family: monospace; background: #ffffff; padding: 8px; border-radius: 4px; color: #4f7cff;">{equation}</div>
                    </div>
                    <div style="background: #fef2f2; padding: 14px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #dc2626;">
                        <strong style="color: #991b1b;">⏱️ RUL Estimate</strong><br>
                        Days Until Replacement: <strong style="font-size: 1.2em; color: #dc2626;">{rul_str}</strong><br>
                        Raw Slope: <strong>{result.get('slope', 0):.4f}°C/ep</strong>
                    </div>
                    {air_quality_html}
                </div>
                """, unsafe_allow_html=True)

            with col2:
                max_deltas = result.get('max_deltas', [])
                cumul_hours = result.get('cumulative_adjusted_hours', [])

                if len(max_deltas) > 2 and len(cumul_hours) == len(max_deltas):
                    fig = go.Figure()
                    fig.add_trace(go.Scatter(
                        x=cumul_hours, y=max_deltas, mode='markers',
                        marker=dict(size=6, color='#a5b4fc', opacity=0.7),
                        name='Max ΔT'
                    ))
                    fig.add_hline(y=result.get('failure_dt', 10.0), line_dash='dot', line_color='#ef4444', annotation_text="Failure Threshold")
                    
                    if len(cumul_hours) >= 2:
                        trend_line = [result.get('baseline_dt', max_deltas[0]) + result.get('slope', 0) * h for h in cumul_hours]
                        fig.add_trace(go.Scatter(x=cumul_hours, y=trend_line, mode='lines', line=dict(color='#4f7cff', width=2, dash='dash'), name='Trend'))

                    fig.update_layout(
                        title=f"ΔT Trend — {site_id}",
                        xaxis_title='Cumulative Adjusted Fan Hours', yaxis_title='ΔT (°C)',
                        height=380, margin=dict(l=40, r=40, t=40, b=40),
                        paper_bgcolor='#ffffff', plot_bgcolor='#fafbfc'
                    )
                    st.plotly_chart(fig, use_container_width=True, config={'displayModeBar': False})
                else:
                    st.info("Not enough episodes for trend plot.")

st.markdown("---")
st.markdown(f"""
<div style="text-align:center;font-size:0.75rem;color:#6b7280;margin-top:2rem;padding:1.5rem;background:#f8fafc;border-radius:8px;border:1px solid #e5e7eb;">
  <strong>Last Updated</strong> {data.get('query_timestamp', 'unknown')}<br>
  Query Time: {data.get('query_elapsed_seconds', '?')}s for {data.get('sites_queried', '?')} sites
</div>
""", unsafe_allow_html=True)
